exec:
  max_threads: 4
  min_output_tasks: 4
in:
  type: file
  path_prefix: C:\Users\Abhishek Gupta\Desktop\github\embulk-output-send_email\calendar.csv
  parser:
    type: csv
    columns:
      - {name: dim_calendar_key, type: long}
      - {name: year_number, type: long}
      - {name: quarter_number, type: long }
      - {name: attr_1, type: string }
filters:
  - type: split_column
    delimiter: '|'
    is_skip: true
    target_key: attr_1
    output_columns:
      - {name: attr1, type: string}
      - {name: attr2, type: string}
      - {name: attr3, type: string}
out:
  type: send_email
  to:
    - abc@gmail.com
    - def@gmail.com
  from: pqr@gmail.com
  password: password
  port: 587
  username: pqr@gmail.com
  host: smtp.gmail.com
  subject: XYZ123
  row: 3
  format_type: html
  protocol: TLSv1.2
  auth: true
  enable_starttls: true
  template: C:\Users\Abhishek Gupta\Desktop\github\embulk-output-send_email\example\email.txt
  is_html: false